spring:
  datasource:
    url: jdbc:mysql://localhost:3306/micromall
    username: root
    password: gendu
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  application:
    name: tulingmall-authcenter
  cloud:
    nacos:
      discovery:
        server-addr: 8.129.222.241:8848
#mybatis:
#  mapper-locations:
#    - classpath:dao/*.xml
#    - classpath*:com/**/mapper/*.xml

mybatis-plus:
  mapper-locations: classpath:dao/*.xml,classpath*:com/**/mapper/*.xml

tuling:
    jwt:
      keyPairName: jwt.jks
      keyPairAlias: jwt
      keyPairSecret: 123456
      keyPairStoreSecret: 123456
server:
  port: 9999


